name: dnd_combat_tracker
description: A high-performance D&D 2024 Combat Tracker.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Persistence
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2

  # UI/UX
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  isar_generator: ^3.1.0+1
  
  # Lints
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
